version: "3"

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.docker-env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    env_file:
      - ./.docker-env
    command: celery -A CSVReconcillationTask.celery worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.docker-env
volumes:
  postgres_data:
