# Generated by Django 5.0 on 2023-12-15 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("file", models.FileField(upload_to="source_files/%Y/%m/%d/")),
                (
                    "target_type",
                    models.CharField(
                        choices=[("Source", "Source"), ("Target", "Target")],
                        default="Source",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Uploaded File",
                "verbose_name_plural": "Uploaded Files",
                "db_table": "uploaded_files",
            },
        ),
        migrations.CreateModel(
            name="SourceData",
            fields=[
                ("created", models.DateTimeField(auto_now=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "file_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reconciliation.fileupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Source Data",
                "verbose_name_plural": "Source Data",
                "db_table": "source_data",
            },
        ),
        migrations.CreateModel(
            name="SourceTargetFilePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pair_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("errors", models.JSONField(blank=True, null=True)),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_pair",
                        to="reconciliation.fileupload",
                    ),
                ),
                (
                    "target_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_pair",
                        to="reconciliation.fileupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Source Target File Pair",
                "verbose_name_plural": "Source Target File Pairs",
                "db_table": "source_target_file_pairs",
            },
        ),
        migrations.CreateModel(
            name="ReconciliationResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=100)),
                ("record_identifier", models.CharField(max_length=100)),
                ("field", models.CharField(max_length=100)),
                ("source_value", models.TextField(null=True)),
                ("target_value", models.TextField(null=True)),
                (
                    "source_target_file_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reconciliation.sourcetargetfilepair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reconciliation Results",
                "verbose_name_plural": "Reconciliation Results",
                "db_table": "reconciliation_results",
            },
        ),
        migrations.CreateModel(
            name="TargetData",
            fields=[
                ("created", models.DateTimeField(auto_now=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "file_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reconciliation.fileupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Target Data",
                "verbose_name_plural": "Target Data",
                "db_table": "target_data",
            },
        ),
    ]
