# Generated by Django 5.0 on 2023-12-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("source_file", models.FileField(upload_to="source_files/%Y/%m/%d/")),
                ("target_file", models.FileField(upload_to="target_files/%Y/%m/%d/")),
            ],
            options={
                "verbose_name": "Uploaded File",
                "verbose_name_plural": "Uploaded Files",
                "db_table": "uploaded_files",
            },
        ),
        migrations.CreateModel(
            name="SourceData",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Source Data",
                "verbose_name_plural": "Source Data",
                "db_table": "source_data",
            },
        ),
        migrations.CreateModel(
            name="TargetData",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Target Data",
                "verbose_name_plural": "Target Data",
                "db_table": "target_data",
            },
        ),
    ]
