# Generated by Django 5.0 on 2023-12-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="errors",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fileupload",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
