# Generated by Django 5.0 on 2023-12-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reconciliation",
            "0004_rename_file_upload_id_sourcedata_file_upload_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcedata",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="targetdata",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
