# Generated by Django 5.0 on 2023-12-15 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation", "0005_alter_sourcedata_id_alter_targetdata_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fileupload",
            old_name="source_file",
            new_name="file",
        ),
        migrations.RemoveField(
            model_name="fileupload",
            name="target_file",
        ),
    ]
