# Generated by Django 5.0 on 2023-12-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation", "0006_rename_source_file_fileupload_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="sourcedata",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="targetdata",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
