# Generated by Django 5.0 on 2023-12-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reconciliation",
            "0007_alter_fileupload_created_alter_sourcedata_created_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=100)),
                ("record_identifier", models.CharField(max_length=100)),
                ("field", models.CharField(max_length=100)),
                ("source_value", models.TextField()),
                ("target_value", models.TextField()),
            ],
            options={
                "verbose_name": "Reconciliation Results",
                "verbose_name_plural": "Reconciliation Results",
                "db_table": "reconciliation_results",
            },
        ),
    ]
