# Generated by Django 5.0 on 2023-12-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation", "0009_fileupload_target_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reconciliationresults",
            name="source_value",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="reconciliationresults",
            name="target_value",
            field=models.TextField(null=True),
        ),
    ]
