# Generated by Django 5.0 on 2023-12-15 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation", "0010_alter_reconciliationresults_source_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileupload",
            name="status",
        ),
        migrations.CreateModel(
            name="SourceTargetFilePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_pair",
                        to="reconciliation.fileupload",
                    ),
                ),
                (
                    "target_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_pair",
                        to="reconciliation.fileupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Source Target File Pair",
                "verbose_name_plural": "Source Target File Pairs",
                "db_table": "source_target_file_pairs",
            },
        ),
    ]
