# Generated by Django 5.0 on 2023-12-15 12:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reconciliation", "0013_reconciliationresults_source_target_file_pair"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcetargetfilepair",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
