# Generated by Django 5.0 on 2023-12-15 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reconciliation", "0014_sourcetargetfilepair_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sourcetargetfilepair",
            old_name="uuid",
            new_name="pair_id",
        ),
    ]
